WITH lista_nomes AS (
    SELECT 1 AS ordem, 'JOSUE TITO PENEDO PANDURO' AS nome
    UNION ALL SELECT 2, 'CLARISSA ANACONA PANDURO'
    UNION ALL SELECT 3, 'ANA MILENA PAJOY ANACONA'
    UNION ALL SELECT 4, 'TITO DIEGO ANACONA PANDURO'
    UNION ALL SELECT 5, 'JOSE MANUEL ANACONA PANDURO'
    UNION ALL SELECT 6, 'DANIEL ANACONA PANDURO'
    UNION ALL SELECT 7, 'MARCOS PEREIRA DO NASCIMENTO'
    UNION ALL SELECT 8, 'MAICON NASCIMENTO FIGUEIRA'
    UNION ALL SELECT 9, 'KELY CRISTINA MOTA FIGUEIRA'
    UNION ALL SELECT 10, 'KELLIANE MOTA DO NASCIMENTO'
    UNION ALL SELECT 11, 'LAURA KEVELLYN MOTA MOURAO'
    UNION ALL SELECT 12, 'EZEQUIEL ALVES MOURAO'
    UNION ALL SELECT 13, 'JACIARA GOMES PINTO'
    UNION ALL SELECT 14, 'JACIELY PINTO DE SOUZA'
    UNION ALL SELECT 15, 'EDSON PINTO DE SOUZA'
    UNION ALL SELECT 16, 'MARIA OSIELE GOMES BONFIM'
    UNION ALL SELECT 17, 'MARILIZA FERREIRA DA SILVA'
    UNION ALL SELECT 18, 'OZANIR VIEIRA DIAS'
    UNION ALL SELECT 19, 'KAILANE DA SILVA DIAS'
    UNION ALL SELECT 20, 'RAIMUNDO DIAS DA SILVA'
    UNION ALL SELECT 21, 'CARMEM RODRIGUES PEREIRA'
    UNION ALL SELECT 22, 'ANA HAICHA RODRIGUES ALVES'
    UNION ALL SELECT 23, 'VITOR EMANUEL RODRIGUES ALVES'
    UNION ALL SELECT 24, 'JAZE ALVES MOURAO'
    UNION ALL SELECT 25, 'MARINHO GABRIEL RODRIGUES ALVES'
    UNION ALL SELECT 26, 'MOISES RODRIGUES ALVES'
    UNION ALL SELECT 27, 'ESTER RODRIGUES ALVES'
    UNION ALL SELECT 28, 'MIRIAN RODRIGUES ALVES'
    UNION ALL SELECT 29, 'GRACIETE SILVA DOS SANTOS'
    UNION ALL SELECT 30, 'MATHEU DO SANTOS GUEDES'
    UNION ALL SELECT 31, 'MARIA VITORIA DOS SANTO DA SILVA'
    UNION ALL SELECT 32, 'NILO OLIVEIRA DUARTE'
    UNION ALL SELECT 33, 'HELENA RODRIGUES BUSTAMANTE'
    UNION ALL SELECT 34, 'NATAN BUSTAMANTE DUARTE'
    UNION ALL SELECT 35, 'VIVIAN RODRIGUES OLIVEIRA'
    UNION ALL SELECT 36, 'LILIAN RODRIGUES OLIVEIRA'
    UNION ALL SELECT 37, 'JORGE BUSTAMANTE DUARTE'
    UNION ALL SELECT 38, 'EDSON MOTA FIGUEIRA'
    UNION ALL SELECT 39, 'LIVONEY MOURAO FIGUEIRA'
    UNION ALL SELECT 40, 'WELYSON MOURAO FIGUEIRA'
    UNION ALL SELECT 41, 'KEZIA ALVES MOURAO'
    UNION ALL SELECT 42, 'NATALY MOURAO FIGUEIRA'
    UNION ALL SELECT 43, 'LYEDSON MOURAO FIGUEIRA'
    UNION ALL SELECT 44, 'WILISON MOURAO FIGUEIRA'
    UNION ALL SELECT 45, 'WETHALLY MAIANE MOURAO FIGUEIRA'
    UNION ALL SELECT 46, 'PRISILA CLAUDETE CARDENO MOTA'
    UNION ALL SELECT 47, 'THANATAN CARDENA MOTA'
    UNION ALL SELECT 48, 'GABRIELA MOTA NUNES'
    UNION ALL SELECT 49, 'MARIA ANITA NASCIMENTO SANTOS MARUBO'
    UNION ALL SELECT 50, 'ELIZETE NASCIMENTO MARUBO'
    UNION ALL SELECT 51, 'ADRIANA FRANCISCA NASCIMENTO MARUBO'
    UNION ALL SELECT 52, 'PAULO DE NASCIMENTO'
    UNION ALL SELECT 53, 'NICANOR NASCIMENTO SANTOS MARUBO'
    UNION ALL SELECT 54, 'SAMIRA NASCIMENTO MARUBO'
    UNION ALL SELECT 55, 'ISRAEL CRUZ DA SILVA MARUBO'
    UNION ALL SELECT 56, 'ROBERTO CRUZ DA SILVA MARUBO'
    UNION ALL SELECT 57, 'ELEN CRUZ DA SILVA'
    UNION ALL SELECT 58, 'FRANCINEIA CRUZ MARUBO'
    UNION ALL SELECT 59, 'WALCINEIA CRUZ DA SILVA MARUBO'
    UNION ALL SELECT 60, 'KARINA CRUZ DA SILVA MARUBO'
    UNION ALL SELECT 61, 'FENIX PAREDES AHUNARI'
    UNION ALL SELECT 62, 'VANUSA BATISTA FREIRE'
    UNION ALL SELECT 63, 'DAME TXAPA MAYURUNA'
    UNION ALL SELECT 64, 'GERSI TXAPA MAYURUNA'
    UNION ALL SELECT 65, 'SADRACK MEO MAYURUNA'
    UNION ALL SELECT 66, 'JOSE MARQUES MEO MAYORUNA'
    UNION ALL SELECT 67, 'ERICA TXAPA MAYRUNA'
    UNION ALL SELECT 68, 'RAIMUNDO JAIR SOUZA RODRIGUES'
    UNION ALL SELECT 69, 'MAYSA CANDIDO IPUCHIMA'
    UNION ALL SELECT 70, 'RAQUEL DE MELO CANDIDO'
    UNION ALL SELECT 71, 'DAVI LUIS CANDIDO RODRIGUES'
    UNION ALL SELECT 72, 'JOSÉ FELIZ DE MELO CANDIDO'
    UNION ALL SELECT 73, 'ESTEFANY NASCIMENTO MARUBO'
    UNION ALL SELECT 74, 'JOSE VIERA DO NASCIMENTO'
    UNION ALL SELECT 75, 'WALCIR DOLES DA SILVA'
    UNION ALL SELECT 76, 'WLCINEIA CRUZ DA SILVA MARUBO'
    UNION ALL SELECT 77, 'ELIZANGELA CRUZ MARUBO'
    UNION ALL SELECT 78, 'ROBERTO CRUZ DA SILVA MARUBO'
    UNION ALL SELECT 79, 'ANA PAULA CRUZ DA SILVA MARUBO'
    UNION ALL SELECT 80, 'RONES DA SILVA MELO'
    UNION ALL SELECT 81, 'TAYLA RANIELLY MENEZES MELO'
    UNION ALL SELECT 82, 'ALDENIZIA DOS REIS MENEZES'
    UNION ALL SELECT 83, 'ADRIANA LINDALVA MOTA MOURÃO'
    UNION ALL SELECT 84, 'ROBERVAN DA SILVA SALINAS'
    UNION ALL SELECT 85, 'ALCIRNEIA DOS SANTOS ROQUE'
    UNION ALL SELECT 86, 'ANE KELLY ROQUE SALINAS'
    UNION ALL SELECT 87, 'VANDERCLEI NOGUEIRA MELO'
    UNION ALL SELECT 88, 'AGATA RAABE SOARES NOGUEIRA'
    UNION ALL SELECT 89, 'RAVI ELIEL SOARES NOGUEIRA'
    UNION ALL SELECT 90, 'ALINE DE SOUZA SOARES'
    UNION ALL SELECT 91, 'BINAN CHAPU SHUNU MATIS'
    UNION ALL SELECT 92, 'KANA MATIS'
    UNION ALL SELECT 93, 'DAMBA MATIS'
    UNION ALL SELECT 94, 'TUMI MATIS'
    UNION ALL SELECT 95, 'RAIMUNDO NONATO COSTA DOS SANTO'
    UNION ALL SELECT 96, 'RAIMUNDO NONATO BORGES DOS SANTO'
    UNION ALL SELECT 97, 'DAVI LUIZ BORGES DOS SANTOS'
    UNION ALL SELECT 98, 'LUZIA BORGES DOS SANTOS'
    UNION ALL SELECT 99, 'RAIMUNDO NONATO BORGES SANTOS'
    UNION ALL SELECT 100, 'AILTON CASTRO NOGUEIRA'
    UNION ALL SELECT 101, 'ROSA GOMES DA CRUZ'
    UNION ALL SELECT 102, 'ARLETE GOMES DE OLIVEIRA'
    UNION ALL SELECT 103, 'LEICIVAN OLIVEIRA DA SILVA'
    UNION ALL SELECT 104, 'HURIAN GABRIEL COSMO PEREIRA DA SILVA'
    UNION ALL SELECT 105, 'THUAN GABRIEL DAMIAO PEREIRA DA SILVA'
    UNION ALL SELECT 106, 'SEBASTIÃO HORACIO DA SILVA'
    UNION ALL SELECT 107, 'REMAN GABRIEL OLIVEIRA DA SILVA'
    UNION ALL SELECT 108, 'LUCIANE DOS SANTOS ROJAS'
    UNION ALL SELECT 109, 'LOHANY ELOA ROJAS AMARAL'
    UNION ALL SELECT 110, 'IZAQUIEL DE SOUZA RODRIGUES'
    UNION ALL SELECT 111, 'IZABELLY LOUISE ROJAS RODRIGUES'
    UNION ALL SELECT 112, 'ADAÍS INÁCIO DO NASCIMENTO'
    UNION ALL SELECT 113, 'ALEX JUNIOR DO NASCIMENTO DIAS'
    UNION ALL SELECT 114, 'JOSUE MESSIAS DO NASCIMENTO DIAS'
    UNION ALL SELECT 115, 'ARAO DIAS DO NASCIMENTO'
    UNION ALL SELECT 116, 'FABRICIO INACIO DO NASCIMENTO'
    UNION ALL SELECT 117, 'VILZANA CALHEIRA DA SILVA'
    UNION ALL SELECT 118, 'TUPA MATIS'
    UNION ALL SELECT 119, 'TUME MATIS'
    UNION ALL SELECT 120, 'SILMARA REIS DAVILA MATIS'
    UNION ALL SELECT 121, 'KANA NETE EPAPA MATIS'
    UNION ALL SELECT 122, 'YASMIN MIRIÃN KANA MATIS'
    UNION ALL SELECT 123, 'BRENDA PAA PINTO'
    UNION ALL SELECT 124, 'TUMI MATIS'
    UNION ALL SELECT 125, 'VALDIR DE SOUZA FREIRE'
    UNION ALL SELECT 126, 'SAMARA DE LIMA FREIRE'
    UNION ALL SELECT 127, 'MARIA SOCORRO ROCHA DE LIMA'
    UNION ALL SELECT 128, 'ELIZA GABRIELLE FREIRE CRUZ'
    UNION ALL SELECT 129, 'SOLANGE DE LIMA FREIRE'
    UNION ALL SELECT 130, 'WENILSON DE LIMA FREIRE'
    UNION ALL SELECT 131, 'MARCOS PAULO GONCALVES FORTZ'
    UNION ALL SELECT 132, 'SOFIA PEMI DE JESUS FORTZ'
    UNION ALL SELECT 133, 'JOSIANE SOUZA DE JESUS'
    UNION ALL SELECT 134, 'LUCAS TUMI DE JESUS FORTZ'
    UNION ALL SELECT 135, 'MARILZA FERREIRA DA SILVA'
    UNION ALL SELECT 136, 'BRYAN SILVA BORGES'
    UNION ALL SELECT 137, 'DAWANA ELOA DA SILVA GOMES'
    UNION ALL SELECT 138, 'DAIRA DA SILVA GOMES'
    UNION ALL SELECT 139, 'JORGEVAN OLIMPIO LIMA'
    UNION ALL SELECT 140, 'ENAIRE DE SOUZA NEVES'
    UNION ALL SELECT 141, 'GIOVANNA NEVES LIMA'
),
-- CTE 2 (NOVA): Pré-filtra os cadastros individuais para pegar APENAS o mais recente de cada pessoa.
UltimoCadastroIndividual AS (
    SELECT
        ci.no_cidadao_filtro,
        ci.nu_micro_area,
        -- Usamos ROW_NUMBER() para "rankear" os cadastros de uma mesma pessoa pela data
        ROW_NUMBER() OVER (
            PARTITION BY LOWER(TRIM(ci.no_cidadao_filtro)) -- Agrupa por nome de cidadão
            ORDER BY ci.dt_cad_individual DESC, ci.co_seq_cds_cad_individual DESC -- O mais recente primeiro
        ) as rn_cad
    FROM
        tb_cds_cad_individual ci
    WHERE
        ci.st_versao_atual = 1 -- Considera apenas as versões ativas
),
-- CTE 3: Faz a busca e junção de todas as tabelas UMA ÚNICA VEZ
DadosCidadao AS (
    SELECT
        l.ordem,
        l.nome,
        c.nu_cns,
        c.nu_cpf,
        c.dt_nascimento,
        e.no_equipe,
        uci.nu_micro_area, -- Pega a microárea da nossa CTE já filtrada
        -- Rankeia os resultados caso um nome da sua lista corresponda a mais de um cidadão
        ROW_NUMBER() OVER (
            PARTITION BY l.nome 
            ORDER BY 
                CASE WHEN LEFT(c.nu_cns, 1) = '7' THEN 1 ELSE 2 END, -- Prioriza CNS que começa com '7'
                c.co_seq_cidadao DESC -- Critério de desempate
        ) as rn
    FROM
        lista_nomes l
    -- Junta a lista de nomes com a tabela de cidadãos
    LEFT JOIN
        tb_cidadao c ON UPPER(c.no_cidadao) = l.nome
    -- Junta para pegar a equipe do vínculo ATUAL do cidadão
    LEFT JOIN 
        tb_cidadao_vinculacao_equipe ve ON ve.co_cidadao = c.co_seq_cidadao
    LEFT JOIN 
        tb_equipe e ON e.nu_ine = ve.nu_ine
    -- Junta com a nossa CTE de cadastros já filtrada e limpa
    LEFT JOIN
        UltimoCadastroIndividual uci ON LOWER(TRIM(uci.no_cidadao_filtro)) = LOWER(TRIM(c.no_cidadao_filtro))
                                     AND uci.rn_cad = 1 -- A MÁGICA ACONTECE AQUI: pega só o cadastro mais recente
)
-- Consulta Final: Formata os dados encontrados
SELECT
    d.nome,
    -- Aplica a mesma lógica de prioridade para CNS/CPF
    COALESCE(
        CASE WHEN LEFT(d.nu_cns, 1) = '7' THEN d.nu_cns ELSE NULL END,
        d.nu_cns,
        CASE 
            WHEN d.nu_cpf IS NOT NULL THEN
                SUBSTRING(LPAD(d.nu_cpf::text, 11, '0'), 1, 3) || '.' ||
                SUBSTRING(LPAD(d.nu_cpf::text, 11, '0'), 4, 3) || '.' ||
                SUBSTRING(LPAD(d.nu_cpf::text, 11, '0'), 7, 3) || '-' ||
                SUBSTRING(LPAD(d.nu_cpf::text, 11, '0'), 10, 2)
            ELSE NULL 
        END,
        ''
    ) AS cns_cpf,
    COALESCE(TO_CHAR(d.dt_nascimento, 'DD/MM/YYYY'), '') AS data_nascimento,
    COALESCE(d.no_equipe, '') AS equipe,
    -- Formata a microárea encontrada (que agora é garantidamente a mais recente)
    COALESCE(
        CASE
            WHEN d.nu_micro_area ~ '^\d+$' THEN d.nu_micro_area::INT
            ELSE 0
        END, 0
    ) AS microarea
FROM
    DadosCidadao d
WHERE
    d.rn = 1 -- Garante que pegamos apenas o melhor resultado para cada nome
ORDER BY
    d.ordem;




