WITH lista_nomes AS (
SELECT 1 AS ordem, 'DIVA PEREIRA DE SOUZA' AS nome
UNION ALL SELECT 2, 'HILDA ANDRADE TENAZOR'
UNION ALL SELECT 3, 'MARIA CANDIDO FERREIRA'
UNION ALL SELECT 4, 'MARIA DE LOURDES CASTRO DA SILVA'
UNION ALL SELECT 5, 'SANDRA CRISTINA WADICK'
UNION ALL SELECT 6, 'MARILIA FERREIRA DA SILVA'
UNION ALL SELECT 7, 'MARIA SUMAITA SAMIAS'
UNION ALL SELECT 8, 'RAIMUNDA NASCIMENTO DA SILVA'
UNION ALL SELECT 9, 'LEILANE DA SILVA MOÇAMBITE'
UNION ALL SELECT 10, 'GLORIA GIMAQUE MIGUEL'
UNION ALL SELECT 11, 'SEBASTIANA LOSANO FERREIRA'
UNION ALL SELECT 12, 'ESTELA TAPAIURI'
UNION ALL SELECT 13, 'DACIRA FIGUEIRA FERREIRA'
UNION ALL SELECT 14, 'JAKSON DOS SANTOS DA SILVA'
UNION ALL SELECT 15, 'BENE DUNU MAYURUNA'
UNION ALL SELECT 16, 'ARTEMIZIA OLIVEIRA DE SOUZA'
UNION ALL SELECT 17, 'CLOVIS RUFINO REIS'
UNION ALL SELECT 18, 'SANDRA PESO MARQUES'
UNION ALL SELECT 19, 'GILBER EUGENIO NARVAEZ HUACH'
UNION ALL SELECT 20, 'LEONILIA VALENTE'
UNION ALL SELECT 21, 'DEUZUILA ALMEIDA'
UNION ALL SELECT 22, 'RAIMUNDO FREITAS RODRIGUES'
UNION ALL SELECT 23, 'MAURICELIO NAPOLES DE MELO'
UNION ALL SELECT 24, 'CARLOS TONICO KANAMARI'
UNION ALL SELECT 25, 'JUAREZ CASTRO BARROSO'
UNION ALL SELECT 26, 'ZULMIRA DE SOUZA FREIRE'
UNION ALL SELECT 27, 'PEDRO DACIO RODRIGUES MELLO'
UNION ALL SELECT 28, 'RAIMUNDA GOMES'
UNION ALL SELECT 29, 'MARIA RODRIGUES DA SILVA'
UNION ALL SELECT 30, 'ALCINA COMAPA BATALHA'
UNION ALL SELECT 31, 'ARACELLI BEATRIZ SEVILLANO ESCUDERO'
UNION ALL SELECT 32, 'RAIMUNDA RAMIRES DOS SANTOS'
UNION ALL SELECT 33, 'ALCINETE TEPA MAYORUNA'
UNION ALL SELECT 34, 'ANA GENE SANGAMA RIOS'
UNION ALL SELECT 35, 'AMARO MELO DO NASCIMENTO'
UNION ALL SELECT 36, 'COSMA GUERREIRO DE MELO'
UNION ALL SELECT 37, 'DIMA SANGAMA RIOS'
UNION ALL SELECT 38, 'FABIANA FERNANDES DE OLIVEIRA'
UNION ALL SELECT 39, 'MARIA DAS GRAÇAS MARIANO LOPES'
UNION ALL SELECT 40, 'JOSELINA LIMA DE OLIVEIRA'
UNION ALL SELECT 41, 'LENDEL FLORENCIO RIBEIRO RODRIGUES'
UNION ALL SELECT 42, 'AUGUSTA FRANCISCA DA COSTA RIBEIRO'
UNION ALL SELECT 43, 'NEZIA FIGUEIRA GOMES'
UNION ALL SELECT 44, 'ANTÔNIA OLIVEIRA GARCIA'
UNION ALL SELECT 45, 'RAIMUNDA MARILIS RODRIGUES NEVES'
UNION ALL SELECT 46, 'ESTER DA SILVA RODRIGUES'
UNION ALL SELECT 47, 'JONAS FREITAS BARBOSA'
UNION ALL SELECT 48, 'ISABEL CRUZ PEREIRA'
UNION ALL SELECT 49, 'RAIMUNDA SALDANHA MENDES'
UNION ALL SELECT 50, 'CESAR DUARTE DOLES MARUBO'
UNION ALL SELECT 51, 'ELSA PINEDO CAHUAZA'
UNION ALL SELECT 52, 'OSMAZILIA DE MELO FELIX'
UNION ALL SELECT 53, 'DOMINGO PEREIRA DE SOUZA'
UNION ALL SELECT 54, 'RAIMUNDA GOMES'
UNION ALL SELECT 55, 'JOAO FILHO DIONISIO CRUZ'
UNION ALL SELECT 56, 'LITA VIRGINIA PANDURO MARIN'
UNION ALL SELECT 57, 'ODETE FIGUEIRA FERREIRA'
UNION ALL SELECT 58, 'REGINA GOMES PINHEIRO'
UNION ALL SELECT 59, 'ROSA GOMES DA CRUZ'
UNION ALL SELECT 60, 'MATILDE GERMANO DA SILVA'
UNION ALL SELECT 61, 'JOSE MARTINS DA SILVA'
UNION ALL SELECT 62, 'MARLIENE MARIA DE ARAUJO'
UNION ALL SELECT 63, 'ALCINEIA LIMA SOARES'
UNION ALL SELECT 64, 'ANDERSON SOUZA MATIAS'
UNION ALL SELECT 65, 'VALDECI SOUZA RIOS'
UNION ALL SELECT 66, 'RONALDO PAIVA RIBEIRO'
UNION ALL SELECT 67, 'ANTONIA FERREIRA MALAFAYA'
UNION ALL SELECT 68, 'DARLY RODRIGUES MELLO'
UNION ALL SELECT 69, 'NEREICY BRAGA CORDEIRO'
UNION ALL SELECT 70, 'ANTONIA OLIVEIRA DE ALMEIDA'
UNION ALL SELECT 71, 'MARIA PERPETUA SOCORRO CHAGAS'
UNION ALL SELECT 72, 'FRANCISCO ALVES CARDENO'
UNION ALL SELECT 73, 'JOAO FARIAS FREIRE DE LIMA'
UNION ALL SELECT 74, 'LUCIMAR NASCIMENTO SARAIVA'
UNION ALL SELECT 75, 'RAQUEL RAMIRES DOS SANTOS'
UNION ALL SELECT 76, 'MARIA CONCEIÇÃO LOPES FREIRE'
UNION ALL SELECT 77, 'ARMANDO LUIS MALAFAYA MACAHUATE'
UNION ALL SELECT 78, 'ALVARO DA SILVA'
UNION ALL SELECT 79, 'MATILDE MARQUES DA SILVA'
UNION ALL SELECT 80, 'MARIA VICTORIA RIVEIRA MOURAO'
UNION ALL SELECT 81, 'NELY HENRIQUE DOS SANTOS'
UNION ALL SELECT 82, 'JOVELINA GOMES DE ALMEIDA'
)

SELECT 
    l.nome,
    COALESCE(
        (SELECT c.nu_cns 
         FROM tb_cidadao c
         WHERE UPPER(unaccent(c.no_cidadao)) LIKE '%' || l.nome || '%'
           AND c.nu_cns IS NOT NULL 
           AND LEFT(c.nu_cns, 1) = '7'
         LIMIT 1),
        (SELECT c.nu_cns 
         FROM tb_cidadao c
         WHERE UPPER(unaccent(c.no_cidadao)) LIKE '%' || l.nome || '%'
           AND c.nu_cns IS NOT NULL
         LIMIT 1),
        (SELECT 
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 1 FOR 3) || '.' ||
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 4 FOR 3) || '.' ||
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 7 FOR 3) || '-' ||
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 10 FOR 2)
         FROM tb_cidadao c
         WHERE UPPER(unaccent(c.no_cidadao)) LIKE '%' || l.nome || '%'
           AND c.nu_cpf IS NOT NULL
         LIMIT 1),
        ''
    ) AS cns_cpf,
    COALESCE(
        (SELECT TO_CHAR(c.dt_nascimento, 'DD/MM/YYYY')
         FROM tb_cidadao c 
         WHERE UPPER(unaccent(c.no_cidadao)) LIKE '%' || l.nome || '%'
         LIMIT 1),
        ''
    ) AS data_nascimento
FROM lista_nomes l
ORDER BY l.ordem;
