WITH lista_nomes AS (
    SELECT 1 AS ordem, 'ADRIANA DA SILVA NOBRE' AS nome
    UNION ALL SELECT 2, 'ADRIANA DE SOUZA CAVALCANTE'
    UNION ALL SELECT 3, 'ALDENETE MARINHO DOS REIS'
    UNION ALL SELECT 4, 'ALDENIZIA SANGAMA DA SILVA'
    UNION ALL SELECT 5, 'ALESSANDRA DE LIMA FREIRE'
    UNION ALL SELECT 6, 'ALESSANDRA MENEGAZZO DE SOUZA'
    UNION ALL SELECT 7, 'ANA CRISTINA GANÇOLVES DE CASTRO'
    UNION ALL SELECT 8, 'ANA JOICE DA SILVA COSTA'
    UNION ALL SELECT 9, 'ANA PAULA PACIDONIO'
    UNION ALL SELECT 10, 'ANDREIA FERREIRA DA SILVA'
    UNION ALL SELECT 11, 'ANETE CASTRO ALVES'
    UNION ALL SELECT 12, 'ANNA KETELYN BARBOSA SANTOS'
    UNION ALL SELECT 13, 'ANTONIA CARNEIRO GOMES'
    UNION ALL SELECT 14, 'AYANA GABRIELA ALVES'
    UNION ALL SELECT 15, 'CARMEN SIQUEIRA SOARES'
    UNION ALL SELECT 16, 'CLINJA DE SOUZA NOGUEIRA'
    UNION ALL SELECT 17, 'DANISMARA SIQUEIRA DE SAMOREIRA'
    UNION ALL SELECT 18, 'EDILAURA DE SOUZA MENESES'
    UNION ALL SELECT 19, 'EDUARDA MELO SIMAS'
    UNION ALL SELECT 20, 'ELIETE ELIAS JUVENAL'
    UNION ALL SELECT 21, 'EUGENIA GOMES FLORES'
    UNION ALL SELECT 22, 'FRANCISCA DANIELE FERREIRA FREITAS'
    UNION ALL SELECT 23, 'HORTENCIA DE MIRANDA SILVA MARREIRA'
    UNION ALL SELECT 24, 'IRES GERMANO DA SILVA'
    UNION ALL SELECT 25, 'JACIRLENE ROBERTO DE SOUZA'
    UNION ALL SELECT 26, 'JAQUELINE ALVES TENAZOR'
    UNION ALL SELECT 27, 'JONAIRA LOPES LEAO'
    UNION ALL SELECT 28, 'JOSEFA RODRIGUES DA FONSECA'
    UNION ALL SELECT 29, 'KAROLINE DE OLIVEIRA FELIX'
    UNION ALL SELECT 30, 'KAROL NOGUERA MELO'
    UNION ALL SELECT 31, 'KELLY MERCEDES LOZANO SANCHEZ'
    UNION ALL SELECT 32, 'LAIDONERIKA WADICK NOBRE FARIAS'
    UNION ALL SELECT 33, 'LEIANE DOS SANTOS SILVA'
    UNION ALL SELECT 34, 'LEIDA MARIA VIANA TENAZOR'
    UNION ALL SELECT 35, 'LIA PRISCILA AMIN BATISTA'
    UNION ALL SELECT 36, 'LUCIA PEREIRA DE SOUZA'
    UNION ALL SELECT 37, 'MAGATETH FELIX TENAZOR'
    UNION ALL SELECT 38, 'MALU LIMA RODRIGUES'
    UNION ALL SELECT 39, 'MARIA DO EGITO GONÇALVES CASTRO BARROS'
    UNION ALL SELECT 40, 'MARIA EVILAZIA DA COSTA SANTOS'
    UNION ALL SELECT 41, 'MARIA IASMIM OLIVEIRA FIGUEREDO'
    UNION ALL SELECT 42, 'MARIA IRANGELITA DA COSTA'
    UNION ALL SELECT 43, 'MARIA JOSE CLEMENTINA DA COSTA'
    UNION ALL SELECT 44, 'MARIA ROSENIR SANTOS SARAIVA'
    UNION ALL SELECT 45, 'MARILENE SOARES DE ANDRADE'
    UNION ALL SELECT 46, 'MARLI FREIRE DE LIMA'
    UNION ALL SELECT 47, 'MARLUCIAR PINHEIRO BATISTA'
    UNION ALL SELECT 48, 'MATILDE GERMANO DA SILVA'
    UNION ALL SELECT 49, 'MIDIAN PEREIRA ROQUE'
    UNION ALL SELECT 50, 'MIRLES DA COSTA MACEDO'
    UNION ALL SELECT 51, 'NATACHA LIANDRA GOMES DA SILVA'
    UNION ALL SELECT 52, 'RAIMUNDA MAMI MARUBO'
    UNION ALL SELECT 53, 'RANNIELA OLIMPIO DA SILVA'
    UNION ALL SELECT 54, 'REGINA GOMES PINHEIRO'
    UNION ALL SELECT 55, 'RITA DA COSTA RODRIGUES'
    UNION ALL SELECT 56, 'RIZONETE GOMES DE SOUZA'
    UNION ALL SELECT 57, 'ROSILENE BATISTA RIBEIRO'
    UNION ALL SELECT 58, 'ROSIMEIRY IRINEU BATISTA'
    UNION ALL SELECT 59, 'TAIRES GERMANO BEZERRA'
    UNION ALL SELECT 60, 'TARSIS NICOL SHAPIANA PINCHE'
    UNION ALL SELECT 61, 'THALIA MARIA FELIX GRACAS'
    UNION ALL SELECT 62, 'VITERCLEIA NOGUEIRA MELO'
    UNION ALL SELECT 63, 'WILDA DA SILVA BARROS'
    UNION ALL SELECT 64, 'WILMARA COROMOTO'
    UNION ALL SELECT 65, 'YARA WALERIA DA SILVA NUNES'
    UNION ALL SELECT 66, 'YUCHI EVERLYN OLIVEIRA REIS'
)
SELECT 
    l.nome,
    COALESCE(
        (SELECT c.nu_cns FROM tb_cidadao c 
         WHERE UPPER(unaccent(c.no_cidadao)) = l.nome
           AND c.nu_cns IS NOT NULL 
           AND LEFT(c.nu_cns, 1) = '7'
         LIMIT 1),
        (SELECT c.nu_cns FROM tb_cidadao c 
         WHERE UPPER(unaccent(c.no_cidadao)) = l.nome
           AND c.nu_cns IS NOT NULL
         LIMIT 1),
        (SELECT 
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 1 FOR 3) || '.' ||
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 4 FOR 3) || '.' ||
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 7 FOR 3) || '-' ||
            SUBSTRING(LPAD(c.nu_cpf::text, 11, '0') FROM 10 FOR 2)
         FROM tb_cidadao c 
         WHERE UPPER(unaccent(c.no_cidadao)) = l.nome
           AND c.nu_cpf IS NOT NULL
         LIMIT 1),
        ''
    ) AS cns_cpf,
    COALESCE(
        (SELECT TO_CHAR(c.dt_nascimento, 'DD/MM/YYYY')
         FROM tb_cidadao c 
         WHERE UPPER(unaccent(c.no_cidadao)) = l.nome
         LIMIT 1),
        ''
    ) AS data_nascimento,
    COALESCE(
        (SELECT e.no_equipe
         FROM tb_cidadao c
         JOIN tb_cidadao_vinculacao_equipe ve ON ve.co_cidadao = c.co_seq_cidadao
         JOIN tb_equipe e ON e.nu_ine = ve.nu_ine
         WHERE UPPER(unaccent(c.no_cidadao)) = l.nome
         LIMIT 1),
        ''
    ) AS equipe,
    COALESCE(
        (SELECT ci.nu_micro_area
         FROM tb_cidadao c
         LEFT JOIN tb_cds_cad_individual ci ON LOWER(TRIM(c.no_cidadao_filtro)) = LOWER(TRIM(ci.no_cidadao_filtro)) AND ci.st_versao_atual = 1
         WHERE UPPER(unaccent(c.no_cidadao)) = l.nome
           AND ci.nu_micro_area IS NOT NULL
         LIMIT 1),
        ''
    ) AS micro_area
FROM lista_nomes l
ORDER BY l.ordem;
